import type { Document, Communication, JiraIssue } from "./types.ts";
import { ACCOUNTS, CONTRACTS, INVOICES, SELLER, PRODUCTS, lineTotal } from "./world.ts";

const money = (n: number) => `$${n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const account = (k: string) => ACCOUNTS.find((a) => a.key === k)!;
const product = (k: string) => PRODUCTS.find((p) => p.key === k)!;
const folder = (accountKey: string) => `/Customers/${account(accountKey).name}`;

// ---------------------------------------------------------------------------------------------
// Documents (Dropbox). Every active contract gets a signed PDF; case-specific documents follow.
// ---------------------------------------------------------------------------------------------
function contractBody(key: string): string[] {
  const c = CONTRACTS.find((x) => x.key === key)!;
  const a = account(c.accountKey);
  return [
    `${c.title}`,
    `Between ${SELLER.name} ("Miny Labs"), ${SELLER.address}, and ${a.legalName} ("Customer").`,
    `Effective date: ${c.startDate}. Term: ${c.termMonths} month(s). Billing: ${c.billing.replace("_", " ")}. Payment terms: ${c.paymentTerms}.`,
    "Fees:",
    ...c.lines.map((l) => `  • ${product(l.productKey).name} — ${l.quantity} × ${money(l.unitAmount)} = ${money(l.quantity * l.unitAmount)}`),
    `Total fees: ${money(lineTotal(c.lines))}${c.discountPct ? ` (includes ${c.discountPct}% discount)` : ""}.`,
    ...(c.poRequired ? [`Purchase order required on invoices${c.poNumber ? `: ${c.poNumber}` : "."}`] : []),
    ...c.clauses,
    `Signed for Customer: ${c.signedBy}.`,
    `Signed for Miny Labs: Hitakshi Arora, Head of Finance, ${SELLER.name}.`,
  ];
}

const contractDocs: Document[] = CONTRACTS.filter((c) => c.status === "active" && c.signedBy !== "unsigned quote").map((c) => ({
  key: `d_${c.key}`,
  accountKey: c.accountKey,
  path: `${folder(c.accountKey)}/Contracts/${c.title.replace(/[/:]/g, "-")} (signed).pdf`,
  title: `${c.title} (signed)`,
  kind: c.title.startsWith("Master") ? "msa" : "order_form",
  versions: [{ date: c.startDate, body: contractBody(c.key) }],
}));

const caseDocs: Document[] = [
  { key: "d_eb_logistics_w9", accountKey: "eastbridge_logistics", path: "/Customers/Eastbridge Logistics/Tax/W-9 Eastbridge Logistics LLC.pdf", title: "Form W-9 — Eastbridge Logistics LLC", kind: "w9", versions: [{ date: "2026-08-16", body: ["Form W-9 (Rev. March 2024) — Request for Taxpayer Identification Number and Certification", "Name: Eastbridge Logistics LLC", "Federal tax classification: LLC taxed as C corporation", "Address: 2200 Channahon Rd, Joliet, IL 60436", "Employer identification number: 84-2917365", "Signature: Daniel Osei, COO — 08/16/2026"] }] },
  { key: "d_eb_holdings_w9", accountKey: "eastbridge_holdings", path: "/Customers/Eastbridge Holdings/Tax/W-9 Eastbridge Holdings Inc.pdf", title: "Form W-9 — Eastbridge Holdings, Inc.", kind: "w9", versions: [{ date: "2025-09-02", body: ["Form W-9 (Rev. March 2024)", "Name: Eastbridge Holdings, Inc.", "Federal tax classification: C corporation", "Address: 150 N Riverside Plaza, Chicago, IL 60606", "Employer identification number: 36-4418207", "Signature: Renata Voss, CFO — 09/02/2025"] }] },
  { key: "d_eb_vendor_form", accountKey: "eastbridge_logistics", path: "/Customers/Eastbridge Logistics/AP/Eastbridge Logistics - Supplier Setup Confirmation.pdf", title: "Supplier setup confirmation — Eastbridge Logistics LLC AP", kind: "correspondence", versions: [{ date: "2026-08-18", body: ["Eastbridge Logistics LLC — Accounts Payable", "Supplier record created: Miny Labs, Inc. (Supplier ID EBL-SUP-10442).", "Bill-to entity for all invoices: Eastbridge Logistics LLC, 2200 Channahon Rd, Joliet, IL 60436.", "Invoices addressed to Eastbridge Holdings, Inc. or other affiliates cannot be matched to this supplier record and will be rejected.", "Send invoices to priya.natarajan@eastbridgelogistics.com."] }] },
  { key: "d_halcyon_vendor_portal", accountKey: "halcyon_bio", path: "/Customers/Halcyon Bio/AP/Halcyon supplier onboarding instructions.pdf", title: "Halcyon Biosciences supplier onboarding", kind: "correspondence", versions: [{ date: "2026-09-11", body: ["Halcyon Biosciences, Inc. — New Supplier Onboarding", "Before the first invoice, suppliers must return a completed W-9 and banking form to ap@halcyonbio.com.", "Invoices must be addressed to Halcyon Biosciences, Inc. (not 'Halcyon Bio').", "Payment terms: Net 45 from receipt of a valid invoice."] }] },
  { key: "d_falcon_po", accountKey: "falcon_aerospace", path: "/Customers/Falcon Aerospace/Purchase Orders/PO-FA-77812.pdf", title: "Purchase Order PO-FA-77812", kind: "po", versions: [{ date: "2026-09-12", body: ["FALCON AEROSPACE CORP. — PURCHASE ORDER", "PO Number: PO-FA-77812   Date: 09/12/2026", "Vendor: Miny Labs, Inc.", "Line 1: Miny Platform Seat (annual) — 60 @ $1,200.00 = $72,000.00", "Line 2: Premium Support (annual) — 1 @ $5,000.00 = $5,000.00", "PO Total: $77,000.00   Terms: Net 45", "Invoices must reference this PO number. Submit to ap@falconaero.com.", "Approved: Rick Dunmore, Procurement Manager"] }] },
  { key: "d_meridian_po_2025", accountKey: "meridian_health", path: "/Customers/Meridian Health System/Purchase Orders/PO-MHS-55120 (FY26).pdf", title: "Purchase Order PO-MHS-55120 (prior year)", kind: "po", versions: [{ date: "2025-09-10", body: ["MERIDIAN HEALTH SYSTEM — PURCHASE ORDER", "PO Number: PO-MHS-55120   Date: 09/10/2025   Fiscal year: FY26", "Vendor: Miny Labs, Inc.", "Miny Platform Seat (annual) — 140 @ $1,200.00 = $168,000.00", "This PO expires 09/30/2026 and cannot be used for renewal invoices."] }] },
  { key: "d_tidewater_amendment", accountKey: "tidewater_energy", path: "/Customers/Tidewater Energy/Contracts/Amendment No. 1 to Order Form TWE-2026-01.pdf", title: "Amendment No. 1 to Order Form TWE-2026-01", kind: "amendment", versions: [
    { date: "2026-09-02", note: "Draft sent for signature", body: ["DRAFT — NOT SIGNED", "Amendment No. 1 to Order Form TWE-2026-01 between Miny Labs, Inc. and Tidewater Energy Partners LP.", "Additional seats: 25 Miny Platform Seats (monthly) at $110.00 per seat per month.", "Effective date of additional seats: September 15, 2026.", "Billing contact remains Luis Carrillo, luis.carrillo@tidewaterenergy.com."] },
    { date: "2026-09-08", note: "Executed version — effective date and billing contact changed", body: ["EXECUTED", "Amendment No. 1 to Order Form TWE-2026-01 between Miny Labs, Inc. and Tidewater Energy Partners LP.", "Additional seats: 25 Miny Platform Seats (monthly) at $110.00 per seat per month, bringing the total to 75 seats.", "Effective date of additional seats: October 1, 2026. No proration for September.", "Billing contact changes to Marisol Vega, Revenue Accounting Manager, billing@tidewaterenergy.com, effective immediately.", "All other terms of Order Form TWE-2026-01 remain unchanged.", "Signed: Hannah Greer, Director, Digital Operations, Tidewater Energy Partners LP — 09/08/2026", "Signed: Hitakshi Arora, Head of Finance, Miny Labs, Inc. — 09/08/2026"] },
  ] },
  { key: "d_crescent_remittance", accountKey: "crescent_dental", path: "/Finance/Remittances/2026-08/Remittance Advice - CDG Partners LLC - 2026-08-29.pdf", title: "Remittance advice — CDG Partners LLC", kind: "remittance", versions: [{ date: "2026-08-29", body: ["CDG PARTNERS LLC — REMITTANCE ADVICE", "Payment date: 08/29/2026   Method: ACH   Trace: 0829-CDG-4471", "Paid to: Miny Labs, Inc.", "On behalf of client practice: Crescent Dental Group, PC", "Invoice INV-2296 — $12,600.00", "Total remitted: $12,600.00"] }] },
  { key: "d_northwind_remittance", accountKey: "northwind_group", path: "/Finance/Remittances/2026-09/Northwind Group - Remittance NWG-WIRE-7730.pdf", title: "Remittance advice — Northwind Group wire NWG-WIRE-7730", kind: "remittance", versions: [{ date: "2026-09-11", body: ["NORTHWIND GROUP HOLDINGS, INC. — TREASURY — REMITTANCE ADVICE", "Wire reference: NWG-WIRE-7730   Value date: 09/11/2026", "INV-2240 (Northwind Retail LLC) — $18,000.00", "INV-2241 (Northwind Health Services LLC) — $15,000.00", "INV-2242 (Northwind Group Holdings, Inc.) — invoiced $9,000.00, paid $8,550.00", "Short-payment on INV-2242: $450.00 — Admin Training Session invoiced at $1,800.00; Enterprise Agreement NWG-2026 price is $1,350.00.", "Total wired: $41,550.00", "Contact: Harold Beck, treasury@northwindgroup.com"] }] },
  { key: "d_lumen_sla", accountKey: "lumen_clinics", path: "/Finance/SLA Reports/2026-08 Availability Report.pdf", title: "August 2026 availability report", kind: "sla_report", versions: [{ date: "2026-09-02", body: ["Miny Labs — Monthly Availability Report — August 2026", "Target: 99.9%. Measured availability (us-east, network plan tenants): 99.30%.", "Incident INC-0822: API outage 08/22/2026 14:05–19:17 UTC (5h12m). Root cause: expired certificate on regional load balancer.", "Affected network-plan tenants: Lumen Clinics Network, Opal Wellness Clinics (standard plan, no SLA).", "Months below target in 2026: August."] }] },
  { key: "d_vantage_usage", accountKey: "vantage_robotics", path: "/Finance/Usage/2026-08 Vantage Robotics usage export.pdf", title: "Vantage Robotics — August 2026 metered usage export", kind: "statement", versions: [{ date: "2026-08-31", body: ["Metered usage export — tenant vantage-prod — August 2026", "Plan allowance: 5,000,000 API calls", "Metered calls: 22,100,000 (includes 13,400,000 calls flagged retry=true by SDK v2.3)", "Overage billed: 17,100 thousand calls × $0.40 = $6,840.00", "Note: metering job version meter-2026.08 counts retried requests. See SCRUM ticket 'Usage meter double-counts retried API calls'."] }] },
  { key: "d_sequoia_old_statement", accountKey: "sequoia_freight", path: "/Customers/Sequoia Freight/Statements/Sequoia Freight statement 2026-08-01.pdf", title: "Statement of account — Sequoia Freight — as of 2026-08-01", kind: "statement", versions: [{ date: "2026-08-01", body: ["Statement of account as of 08/01/2026", "INV-2231 — issued 07/25/2026 — due 08/24/2026 — $31,000.00 — open", "Balance due: $31,000.00", "Sent to: tom.reyes@sequoiafreight.com"] }] },
  { key: "d_atlas_ap_rules", accountKey: "atlas_pharma", path: "/Customers/Atlas Pharma/AP/Atlas Pharma US - Invoice Requirements.pdf", title: "Atlas Pharma US — invoice requirements", kind: "correspondence", versions: [{ date: "2026-08-12", body: ["Atlas Pharma US, Inc. — Supplier Invoice Requirements", "Every invoice must show: legal name Atlas Pharma US, Inc.; federal EIN 56-2290714; PO or contract reference.", "Invoices missing the EIN are automatically rejected by our AP platform and are not considered received."] }] },
  { key: "d_orchid_renewal_notice", accountKey: "orchid_legal", path: "/Customers/Orchid Legal/Correspondence/Renewal notice sent 2026-08-10.pdf", title: "Renewal notice — Orchid Legal", kind: "correspondence", versions: [{ date: "2026-08-10", body: ["Renewal notice sent to tmarsh@orchidlegal.com on 08/10/2026.", "Your subscription renews on 09/10/2026 for 10 seats at $1,284.00 per seat per year (7% uplift per Order Form OL-2025).", "No response received."] }] },
  { key: "d_globex_name_change", accountKey: "globex_systems", path: "/Customers/Globex Systems/Legal/Globex name change notice 2026-06-03.pdf", title: "Globex name change notice", kind: "correspondence", versions: [{ date: "2026-06-03", body: ["Notice of corporate name change", "Effective June 1, 2026, Globex Corporation is renamed Globex Systems, Inc. Federal EIN 37-1150042 is unchanged.", "Please update invoices and records accordingly. Existing agreements continue in force."] }] },
  { key: "d_ar_aging_snapshot", path: "/Finance/Reports/AR aging snapshot 2026-08-31 (stale).pdf", title: "AR aging snapshot — 2026-08-31", kind: "statement", versions: [{ date: "2026-08-31", body: ["AR aging snapshot exported 08/31/2026 — for reference only; QuickBooks is the system of record.", "Kestrel Foods INV-2335 $54,000 1–30 days", "Copperleaf Supply INV-2150 $9,750 31–60 days", "Harbor & Pine INV-2204 $18,400 31–60 days", "Orion Dental Labs INV-1990 $2,400 61–90 days"] }] },
];

export const DOCUMENTS: Document[] = [...contractDocs, ...caseDocs];

// ---------------------------------------------------------------------------------------------
// Communications: HubSpot emails/notes (customer conversations) and Slack (internal).
// ---------------------------------------------------------------------------------------------
export const COMMUNICATIONS: Communication[] = [
  // Eastbridge
  { key: "m_eb_reject", accountKey: "eastbridge_logistics", channel: "hubspot_email", direction: "inbound", date: "2026-09-11T15:42:00Z", from: "priya.natarajan@eastbridgelogistics.com", to: SELLER.arEmail, subject: "RE: Invoice INV-2381 from Miny Labs — REJECTED (bill-to entity)", body: "Hello,\n\nWe are returning invoice INV-2381 ($101,000.00) unpaid. It is addressed to Eastbridge Holdings, Inc. Our order form EBL-2026-01 and supplier record EBL-SUP-10442 are with Eastbridge Logistics LLC (EIN 84-2917365), and our AP system cannot match an invoice to a different legal entity.\n\nPlease send a corrected invoice addressed to Eastbridge Logistics LLC. Once we receive it we can schedule payment in our next run.\n\nThanks,\nPriya Natarajan\nAccounts Payable Lead, Eastbridge Logistics LLC" },
  { key: "m_eb_holdings_remit", accountKey: "eastbridge_holdings", channel: "hubspot_email", direction: "inbound", date: "2026-09-10T13:05:00Z", from: "ap@eastbridge.com", to: SELLER.arEmail, subject: "Payment sent — Eastbridge Holdings", body: "Hi Miny Labs team,\n\nACH payment of $24,000.00 was released today for our annual renewal. Reference EBH-ACH-240910.\n\nGary Lindqvist\nAP Manager, Eastbridge Holdings, Inc." },
  { key: "m_eb_slack_ae", accountKey: "eastbridge_logistics", channel: "slack", slackChannel: "assignments", date: "2026-09-12T16:05:00Z", from: "Marcus Bell (Account Executive)", body: "Heads up: Eastbridge's ops team says their AP bounced the big fleet rollout invoice — something about it going to the wrong company. We're talking expansion with Holdings next week, so I'd love this cleaned up quietly. Peeblo, can you take it?" },
  // Pinecrest / Halcyon
  { key: "m_pc_note", accountKey: "pinecrest_analytics", channel: "slack", slackChannel: "assignments", date: "2026-09-02T18:20:00Z", from: "Marcus Bell (Account Executive)", body: "Pinecrest signed yesterday 🎉 60k incl. implementation. Kickoff is on the 16th." },
  { key: "m_hb_note", accountKey: "halcyon_bio", channel: "slack", slackChannel: "assignments", date: "2026-09-10T21:10:00Z", from: "Aisha Rahman (Account Executive)", body: "Halcyon closed today, 30 seats. Mei is the day-to-day contact. They mentioned some supplier onboarding thing — I forwarded the PDF to Dropbox." },
  // Quarry
  { key: "m_ql_renewal", accountKey: "quarry_labs", channel: "hubspot_note", date: "2026-09-08T17:00:00Z", from: "Aisha Rahman", body: "Renewal signed. Tess pushed hard on price — we agreed to hold the 20% multi-year discount ($960/seat) for 30 seats. Invoice should go out on the 15th." },
  // Meridian / Falcon
  { key: "m_mh_slack", accountKey: "meridian_health", channel: "slack", slackChannel: "assignments", date: "2026-09-09T15:30:00Z", from: "Marcus Bell (Account Executive)", body: "Meridian renewal is signed. Gloria in procurement says the FY27 PO is 'in approval' — she thinks next week. Don't send anything without the PO or it bounces like last year." },
  { key: "m_mh_procurement", accountKey: "meridian_health", channel: "hubspot_email", direction: "inbound", date: "2026-09-10T14:12:00Z", from: "gloria.hendricks@meridianhealth.org", to: SELLER.arEmail, subject: "FY27 PO status — Miny Labs renewal", body: "Hi,\n\nThe FY27 requisition for Miny Labs (150 seats) is with our finance committee. I expect a PO number by September 18. Please hold the invoice until then; invoices without a PO are returned automatically.\n\nGloria Hendricks\nSenior Procurement Specialist" },
  { key: "m_fa_po", accountKey: "falcon_aerospace", channel: "hubspot_email", direction: "inbound", date: "2026-09-12T19:48:00Z", from: "rick.dunmore@falconaero.com", to: SELLER.arEmail, subject: "PO-FA-77812 for Miny Labs engineering rollout", body: "Attached is PO-FA-77812 for $77,000.00. Please reference it on your invoice and send to ap@falconaero.com. I've also saved a copy to the shared folder.\n\nRick Dunmore, Procurement Manager" },
  // Tidewater
  { key: "m_te_amend", accountKey: "tidewater_energy", channel: "hubspot_email", direction: "inbound", date: "2026-09-08T20:15:00Z", from: "hannah.greer@tidewaterenergy.com", to: SELLER.arEmail, subject: "Signed: Amendment No. 1", body: "Signed amendment attached. Note we moved the start of the 25 new seats to October 1 since the field teams won't onboard until then. Also, please send invoices to Marisol in revenue accounting from now on.\n\nHannah" },
  // Solstice
  { key: "m_sm_stripe_note", accountKey: "solstice_media", channel: "hubspot_note", date: "2026-09-01T09:00:00Z", from: "Stripe (automated)", body: "Invoice INV-2377 payment failed: card_declined (generic_decline). Smart Retries enabled." },
  // Harbor & Pine — promise to pay
  { key: "m_hp_reminder1", accountKey: "harbor_pine", channel: "hubspot_email", direction: "outbound", date: "2026-08-07T14:00:00Z", from: SELLER.arEmail, to: "elena.rossi@harborandpine.com", subject: "Reminder: INV-2204 is past due", body: "Hi Elena, a friendly reminder that INV-2204 for $18,400.00 was due on July 31. Please let us know when payment is scheduled." },
  { key: "m_hp_reminder2", accountKey: "harbor_pine", channel: "hubspot_email", direction: "outbound", date: "2026-08-28T14:00:00Z", from: SELLER.arEmail, to: "elena.rossi@harborandpine.com", subject: "Second reminder: INV-2204", body: "Hi Elena, following up on INV-2204 ($18,400.00), now 28 days past due." },
  { key: "m_hp_promise", accountKey: "harbor_pine", channel: "hubspot_email", direction: "inbound", date: "2026-09-08T16:30:00Z", from: "elena.rossi@harborandpine.com", to: SELLER.arEmail, subject: "RE: Second reminder: INV-2204", body: "Apologies for the delay — our seasonal cash cycle. INV-2204 is approved and scheduled in our payment run on Friday, September 18. You'll see the ACH that day.\n\nElena Rossi, Controller" },
  // Copperleaf — broken promise
  { key: "m_cl_reminder", accountKey: "copperleaf_supply", channel: "hubspot_email", direction: "outbound", date: "2026-08-25T14:00:00Z", from: SELLER.arEmail, to: "doug.pruitt@copperleafsupply.com", subject: "INV-2150 is 42 days past due", body: "Hi Doug, INV-2150 for $9,750.00 was due July 14. Can you share a payment date?" },
  { key: "m_cl_promise", accountKey: "copperleaf_supply", channel: "hubspot_email", direction: "inbound", date: "2026-08-29T18:02:00Z", from: "doug.pruitt@copperleafsupply.com", to: SELLER.arEmail, subject: "RE: INV-2150 is 42 days past due", body: "Sorry! Check will go out Friday Sept 5. — Doug" },
  // Brightline — paid via Stripe, reminder would be wrong
  { key: "m_bl_reminder", accountKey: "brightline_studios", channel: "hubspot_email", direction: "outbound", date: "2026-08-20T14:00:00Z", from: SELLER.arEmail, to: "kira@brightlinestudios.tv", subject: "Reminder: INV-2318 past due", body: "Hi Kira, INV-2318 for $6,200.00 was due August 6. You can pay by card using the invoice link." },
  { key: "m_bl_paid", accountKey: "brightline_studios", channel: "hubspot_email", direction: "inbound", date: "2026-09-12T22:40:00Z", from: "kira@brightlinestudios.tv", to: SELLER.arEmail, subject: "RE: Reminder: INV-2318 past due", body: "Paid it with the card link just now, sorry for the wait!" },
  // Crescent — already paid by a different payer
  { key: "m_cd_reminder", accountKey: "crescent_dental", channel: "hubspot_email", direction: "outbound", date: "2026-09-03T14:00:00Z", from: SELLER.arEmail, to: "billing@crescentdental.com", subject: "Reminder: INV-2296 past due", body: "Hi Monica, INV-2296 for $12,600.00 was due August 27." },
  { key: "m_cd_claim", accountKey: "crescent_dental", channel: "hubspot_email", direction: "inbound", date: "2026-09-10T17:25:00Z", from: "billing@crescentdental.com", to: SELLER.arEmail, subject: "RE: Reminder: INV-2296 past due — WE PAID", body: "Hi,\n\nThis was paid on August 29 by ACH through our management company. Trace number 0829-CDG-4471, $12,600.00. Please stop sending reminders.\n\nMonica Delgado" },
  // Ridgeview
  { key: "m_rc_note", accountKey: "ridgeview_capital", channel: "hubspot_note", date: "2026-09-08T12:00:00Z", from: "Aisha Rahman", body: "Sofia said Ridgeview Capital's partner approval for INV-2293 is pending; expect payment late September." },
  // Northwind
  { key: "m_nw_treasury", accountKey: "northwind_group", channel: "hubspot_email", direction: "inbound", date: "2026-09-11T16:00:00Z", from: "treasury@northwindgroup.com", to: SELLER.arEmail, subject: "Wire NWG-WIRE-7730 — remittance advice", body: "Please find our remittance advice for wire NWG-WIRE-7730 ($41,550.00) covering INV-2240, INV-2241 and INV-2242. We short-paid INV-2242 by $450.00: the training session should be $1,350.00 per our Enterprise Agreement. The advice is in your shared folder.\n\nHarold Beck, Assistant Treasurer" },
  // Vantage
  { key: "m_vr_dispute", accountKey: "vantage_robotics", channel: "hubspot_email", direction: "inbound", date: "2026-09-09T15:10:00Z", from: "grace.liu@vantagerobotics.ai", to: SELLER.arEmail, subject: "Dispute: API overage on INV-2270", body: "Hi,\n\nWe dispute the $6,840.00 API overage on INV-2270. Our order form caps overage at $2,500.00 per month, and our engineers see your SDK retries being counted as separate calls. We will pay the seat charges ($4,950.00) on time. Please send a corrected invoice or credit.\n\nGrace Liu, VP Finance" },
  // Lumen
  { key: "m_lc_credit", accountKey: "lumen_clinics", channel: "hubspot_email", direction: "inbound", date: "2026-09-05T13:30:00Z", from: "dana.whitaker@lumenclinics.com", to: SELLER.arEmail, subject: "SLA credit request — August outage", body: "Our clinics lost scheduling access for five hours on August 22. Per our agreement's SLA we are requesting the service credit for August. Please apply it to our next invoice.\n\nDana Whitaker" },
  // Orchid
  { key: "m_ol_question", accountKey: "orchid_legal", channel: "hubspot_email", direction: "inbound", date: "2026-09-12T18:00:00Z", from: "tmarsh@orchidlegal.com", to: SELLER.arEmail, subject: "Question about invoice INV-2384", body: "Hi, our renewal invoice is $12,840 but last year we paid $12,000 for the same 10 seats. Is this a mistake? — Theo" },
  // Sequoia
  { key: "m_sf_bounce", accountKey: "sequoia_freight", channel: "hubspot_note", date: "2026-08-30T10:00:00Z", from: "HubSpot (automated)", body: "Email to tom.reyes@sequoiafreight.com bounced: 550 5.1.1 mailbox does not exist." },
  { key: "m_sf_statement_req", accountKey: "sequoia_freight", channel: "hubspot_email", direction: "inbound", date: "2026-09-13T15:20:00Z", from: "carmen.ortiz@sequoiafreight.com", to: SELLER.arEmail, subject: "Statement request", body: "Hello, I took over AP from Tom Reyes. Can you send a current statement of all open Miny Labs invoices for Sequoia Freight Lines so I can reconcile before our month-end? Thanks, Carmen Ortiz" },
  // Keystone
  { key: "m_ka_receipt", accountKey: "keystone_apparel", channel: "hubspot_note", date: "2026-09-09T11:00:00Z", from: "Stripe (automated)", body: "Payment received for INV-2366: $4,200.00 by card." },
  // Beacon
  { key: "m_bs_question", accountKey: "beacon_schools", channel: "hubspot_email", direction: "inbound", date: "2026-09-12T16:45:00Z", from: "finance@beaconschools.org", to: SELLER.arEmail, subject: "Two invoices with the same number?", body: "Our QuickBooks vendor statement from you shows INV-2299 and INV-2299-1, both $9,600 for the same 8 seats. We only owe one, right? We'll pay INV-2299 by the due date. — Latoya" },
  // Atlas
  { key: "m_ap_reject", accountKey: "atlas_pharma", channel: "hubspot_email", direction: "inbound", date: "2026-08-28T09:15:00Z", from: "ap-us@atlaspharma.com", to: SELLER.arEmail, subject: "Invoice INV-2263 rejected — missing EIN", body: "Invoice INV-2263 was rejected by our AP platform because it does not display our federal EIN 56-2290714. Please reissue with the EIN shown. The due date will be reset when we receive a valid invoice.\n\nIngrid Bauer, AP Team Lead" },
  { key: "m_ap_slack", accountKey: "atlas_pharma", channel: "slack", slackChannel: "assignments", date: "2026-09-05T17:00:00Z", from: "Hitakshi Arora (Head of Finance)", body: "Atlas needs their EIN on invoices. Eng ticket is open for the invoice template custom field. Nothing we can send until that lands." },
  // Kestrel / Orion
  { key: "m_od_reminder3", accountKey: "orion_dental", channel: "hubspot_email", direction: "outbound", date: "2026-08-26T14:00:00Z", from: SELLER.arEmail, to: "rafael@oriondentallabs.com", subject: "Final reminder: INV-1990", body: "Hi Rafael, INV-1990 for $2,400.00 is now 76 days past due. Please contact us to arrange payment." },
  // Lookalike noise
  { key: "m_ebc_hello", accountKey: "east_bridge_coffee", channel: "hubspot_email", direction: "inbound", date: "2026-09-02T12:00:00Z", from: "molly@eastbridgecoffee.com", to: SELLER.arEmail, subject: "Update card on file", body: "Hi! I updated our card in the portal, just confirming nothing else is needed. — Molly, East Bridge Coffee" },
  { key: "m_globex_ap", accountKey: "globex_systems", channel: "hubspot_email", direction: "inbound", date: "2026-06-05T12:00:00Z", from: "ap@globex.com", to: SELLER.arEmail, subject: "Name change — Globex Systems", body: "Please update our name to Globex Systems, Inc. on future invoices. Same EIN. Notice attached. — Hank" },
  // Internal chatter
  { key: "m_slack_close", channel: "slack", slackChannel: "assignments", date: "2026-09-01T16:00:00Z", from: "Hitakshi Arora (Head of Finance)", body: "August close is done. Reminder: Peeblo owns US receivables now — collections, cash application and billing exceptions. Anything over its authority comes to #ar-approvals." },
  { key: "m_slack_sync", channel: "slack", slackChannel: "assignments", date: "2026-08-22T20:30:00Z", from: "Dev Patel (Engineering)", body: "FYI the Stripe → QuickBooks sync job hit rate limits on Aug 21 and retried a batch. Should be fine but flag anything weird in QBO." },
];

// ---------------------------------------------------------------------------------------------
// Jira (project SCRUM). Engineering and cross-team dependencies.
// ---------------------------------------------------------------------------------------------
export const JIRA_ISSUES: JiraIssue[] = [
  { key: "j_meter_bug", accountKey: "vantage_robotics", type: "Task", summary: "Usage meter double-counts retried API calls (SDK v2.3)", status: "In Progress", labels: ["billing-impact", "metering"], created: "2026-09-03", description: "Metering job meter-2026.08 counts requests with retry=true as separate billable calls. Affects tenants on SDK >= 2.3. Known affected in August: vantage-prod (13.4M retried calls), sequoia-dispatch (2.1M). Fix: dedupe on request_id before aggregation. Billing impact to be quantified per tenant.", comments: [{ date: "2026-09-04", author: "Dev Patel", body: "Confirmed on vantage-prod: 13,400,000 of 22,100,000 August calls are retries. Corrected overage would be 3,700 thousand calls." }, { date: "2026-09-10", author: "Dev Patel", body: "Fix merged behind flag; backfill of corrected August numbers ETA Sep 17." }] },
  { key: "j_invoice_ein", accountKey: "atlas_pharma", type: "Story", summary: "Invoice template: show customer tax ID (EIN/VAT) custom field", status: "In Progress", labels: ["billing", "blocked"], created: "2026-08-29", description: "Some enterprise customers (Atlas Pharma US) reject invoices without their tax ID. Add customer tax ID to Stripe invoice custom fields and PDF template.", comments: [{ date: "2026-09-01", author: "Dev Patel", body: "Needs Stripe invoice rendering settings change + template QA. Waiting on design review." }, { date: "2026-09-05", author: "Hitakshi Arora", body: "Atlas invoice INV-2263 blocked on this. Any ETA?" }] },
  { key: "j_incident_0822", accountKey: "lumen_clinics", type: "Task", summary: "INC-0822: API outage us-east 08/22 (5h12m) — postmortem", status: "Done", labels: ["incident", "sla"], created: "2026-08-22", description: "Expired certificate on regional load balancer caused API outage 14:05–19:17 UTC. Network-plan tenants with SLA: Lumen Clinics Network. Customer credits per contract to be handled by Finance.", comments: [{ date: "2026-08-25", author: "Dev Patel", body: "Postmortem published. Cert automation added." }] },
  { key: "j_sync_retry", type: "Task", summary: "Stripe → QuickBooks sync: make invoice creation idempotent on retry", status: "To Do", labels: ["billing", "sync"], created: "2026-08-23", description: "During the Aug 21 rate-limit event the sync job retried invoice creation. Investigate whether any QuickBooks invoices were duplicated. Proposed fix: key QBO invoice creation on Stripe invoice ID." },
  { key: "j_sync_payments", type: "Task", summary: "Stripe → QuickBooks sync: card payments after Sep 8 not posting", status: "To Do", labels: ["billing", "sync"], created: "2026-09-13", description: "Reported by Finance: some Stripe card payments since Sep 8 have not created QuickBooks payments. Needs investigation." },
  { key: "j_dunning", type: "Story", summary: "Refresh dunning email templates", status: "To Do", labels: ["billing"], created: "2026-07-15", description: "Update reminder copy to match new collections policy tone." },
  { key: "j_q3_close", type: "Task", summary: "Q3 revenue close checklist", status: "In Progress", labels: ["finance"], created: "2026-09-01", description: "Deferred revenue schedule, usage accruals, credit memo review, AR reserve." },
  { key: "j_tax", type: "Story", summary: "Enable Stripe Tax for EU customers", status: "To Do", labels: ["billing", "tax"], created: "2026-06-10", description: "Not relevant to US entity yet." },
  { key: "j_po_field", type: "Task", summary: "Add PO number field to Stripe invoice template", status: "Done", labels: ["billing"], created: "2026-05-02", description: "PO number is set via invoice custom field 'PO Number'.", comments: [{ date: "2026-05-20", author: "Dev Patel", body: "Shipped. Use custom_fields name 'PO Number'." }] },
  { key: "j_ebl_renewal_sso", accountKey: "eastbridge_holdings", type: "Task", summary: "Eastbridge Holdings expansion: SSO security review", status: "To Do", labels: ["sales-support"], created: "2026-09-09", description: "Security questionnaire for warehouse analytics expansion." },
];
