/**
 * CitationDetailModal - the "clicky citation" sketch made real.
 *
 * Opens when the operator clicks an inline [n] chip in the Brief.
 * Shows three things:
 *
 *   1. The source's logo + brand name - they instantly recognise where
 *      this evidence came from. (SourceIcon + sources.ts metadata.)
 *
 *   2. A "Go check" button - deep-links straight to the source record
 *      (Stripe charge, Notion page, HubSpot contact, etc.). Built by
 *      services/citation_links.py on the backend; we just open the url.
 *
 *   3. "Why this matters" - a 2-3 sentence plain-English explanation
 *      generated by Gemini Flash 3.1 Lite using the case context + the
 *      surrounding finding text. Cached server-side in the
 *      citation_reasonings table so re-clicks are instant.
 *
 * Loading state: skeleton lines for the reasoning while the LLM thinks
 * (typically 600-1500ms on cache miss, 30-80ms on hit).
 */

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { ExternalLink, X } from "lucide-react";

import { SourceIcon } from "@/components/ui/SourceIcon";
import { getSource } from "@/lib/sources";
import {
  fetchCitationReasoning,
  type CitationReasoning,
} from "@/lib/api";

export interface CitationDetailRequest {
  caseId: string;
  source: string;
  table: string | null;
  ref: string | null;
  field: string | null;
  url: string | null;
  /** The finding sentence that referenced this citation. Used in the
      modal header so the reader sees the claim before the evidence. */
  findingText?: string | null;
  /** The 1-based citation number from the Brief. */
  n?: number;
}

export interface CitationDetailModalProps {
  request: CitationDetailRequest | null;
  onClose: () => void;
}

export function CitationDetailModal({
  request,
  onClose,
}: CitationDetailModalProps) {
  const [reasoning, setReasoning] = useState<CitationReasoning | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Reset state every time a different chip opens the modal.
  useEffect(() => {
    if (!request) return;
    setReasoning(null);
    setError(null);

    // Without table+ref we can't fetch - show the deep link only.
    if (!request.table || !request.ref) {
      return;
    }

    let cancelled = false;
    setLoading(true);
    fetchCitationReasoning(request.caseId, {
      source: request.source,
      table: request.table,
      ref: request.ref,
      field: request.field,
    })
      .then((r) => {
        if (cancelled) return;
        setReasoning(r);
      })
      .catch((e) => {
        if (cancelled) return;
        setError((e as Error).message);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [request]);

  // Close on Escape.
  useEffect(() => {
    if (!request) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [request, onClose]);

  const sourceMeta = request ? getSource(request.source) : null;
  const sourceName = sourceMeta?.name ?? request?.source ?? "Source";

  return (
    <AnimatePresence>
      {request && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.15 }}
          className="fixed inset-0 z-[60] flex items-center justify-center p-4"
          style={{ background: "rgba(0,0,0,0.55)" }}
          onClick={onClose}
        >
          <motion.div
            initial={{ opacity: 0, y: 8, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 4, scale: 0.98 }}
            transition={{ duration: 0.18 }}
            className="w-full max-w-[520px] overflow-hidden"
            style={{
              background: "var(--color-surface-2)",
              border: "1px solid var(--color-rule)",
              borderRadius: "var(--radius-md)",
              boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
            }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header: logo, source name, citation number, close */}
            <div
              className="flex items-start gap-3 px-5 pt-4 pb-3 border-b"
              style={{ borderColor: "var(--color-rule-soft)" }}
            >
              <div
                className="flex items-center justify-center shrink-0"
                style={{
                  width: 36,
                  height: 36,
                  background: "var(--color-surface)",
                  border: "1px solid var(--color-rule-soft)",
                  borderRadius: "var(--radius-sm)",
                }}
              >
                <SourceIcon id={request.source} size={18} tinted />
              </div>
              <div className="flex-1 min-w-0">
                <div
                  className="eyebrow"
                  style={{ color: "var(--color-ink-faint)" }}
                >
                  Citation
                  {typeof request.n === "number" && (
                    <span className="ml-2 tabular-nums">[{request.n}]</span>
                  )}
                </div>
                <div
                  className="text-[14px] mt-0.5 truncate"
                  style={{ color: "var(--color-ink-strong)" }}
                >
                  {sourceName}
                </div>
                {(request.table || request.ref) && (
                  <div
                    className="font-mono text-[10.5px] tabular-nums mt-0.5 truncate"
                    style={{ color: "var(--color-ink-faint)" }}
                  >
                    {request.table}
                    {request.table && request.ref && " / "}
                    {request.ref}
                    {request.field && (
                      <span style={{ color: "var(--color-ink-ghost)" }}>
                        {" · "}
                        {request.field}
                      </span>
                    )}
                  </div>
                )}
              </div>
              <button
                onClick={onClose}
                aria-label="Close"
                className="shrink-0 -mt-1 -mr-1 p-1 rounded hover:bg-[color:var(--color-surface)]"
                style={{ color: "var(--color-ink-muted)" }}
              >
                <X size={14} />
              </button>
            </div>

            {/* Body: open-in-source (primary verify action) → finding →
                reasoning. Verification is the operator's first need: see
                the actual record, not the agent's interpretation. */}
            <div className="px-5 py-4 space-y-4">
              {request.url ? (
                <a
                  href={request.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={
                    "flex items-center justify-between gap-3 px-3 py-2.5 " +
                    "transition-colors hover:opacity-90 outline-none " +
                    "focus-visible:ring-2 focus-visible:ring-offset-2 " +
                    "focus-visible:ring-[color:var(--color-accent)] " +
                    "focus-visible:ring-offset-[color:var(--color-surface-2)]"
                  }
                  style={{
                    background: "var(--color-accent)",
                    color: "var(--color-accent-ink)",
                    borderRadius: "var(--radius-sm)",
                  }}
                >
                  <span className="inline-flex items-center gap-2 min-w-0">
                    <span
                      className="text-[10px] uppercase tracking-[0.14em]"
                      style={{ opacity: 0.78 }}
                    >
                      Open in source
                    </span>
                    <span className="text-[13px] truncate">
                      Verify in {sourceName}
                    </span>
                  </span>
                  <ExternalLink size={14} />
                </a>
              ) : (
                <div
                  className="flex items-center justify-between gap-3 px-3 py-2.5"
                  style={{
                    background: "var(--color-surface)",
                    border: "1px dashed var(--color-rule)",
                    borderRadius: "var(--radius-sm)",
                  }}
                >
                  <span
                    className="text-[12px] italic"
                    style={{ color: "var(--color-ink-faint)" }}
                  >
                    No direct link for this record - open the source manually.
                  </span>
                </div>
              )}

              {request.findingText && (
                <div>
                  <div
                    className="eyebrow"
                    style={{ color: "var(--color-ink-faint)" }}
                  >
                    Referenced from
                  </div>
                  <p
                    className="mt-1 font-display italic text-[13px] leading-[1.55]"
                    style={{ color: "var(--color-ink-muted)" }}
                  >
                    {request.findingText}
                  </p>
                </div>
              )}

              <div>
                <div
                  className="eyebrow"
                  style={{ color: "var(--color-ink-faint)" }}
                >
                  Why this matters
                </div>
                <div className="mt-1.5">
                  {loading && <ReasoningSkeleton />}
                  {!loading && error && (
                    <p
                      className="text-[12.5px]"
                      style={{ color: "var(--color-danger)" }}
                    >
                      Couldn&apos;t generate reasoning: {error}
                    </p>
                  )}
                  {!loading && !error && reasoning && (
                    <p
                      className="font-display text-[14px] leading-[1.55]"
                      style={{ color: "var(--color-ink-strong)" }}
                    >
                      {reasoning.reasoning}
                    </p>
                  )}
                  {!loading &&
                    !error &&
                    !reasoning &&
                    (!request.table || !request.ref) && (
                      <p
                        className="text-[12.5px] italic"
                        style={{ color: "var(--color-ink-faint)" }}
                      >
                        No structured citation on this finding - open the
                        source to inspect manually.
                      </p>
                    )}
                </div>
                {!loading && reasoning && (
                  <div
                    className="mt-2 text-[10px] tabular-nums"
                    style={{
                      color: "var(--color-ink-ghost)",
                      letterSpacing: "0.04em",
                    }}
                  >
                    {reasoning.cached ? "Cached" : "Just generated"}
                    {reasoning.model && (
                      <>
                        {" · "}
                        <span className="font-mono">{reasoning.model}</span>
                      </>
                    )}
                  </div>
                )}
              </div>
            </div>

            {/* Footer - quiet metadata strip, no actions (action moved
                to the top of the body where verification belongs). */}
            <div
              className="px-5 py-3 border-t flex items-center justify-between gap-3"
              style={{ borderColor: "var(--color-rule-soft)" }}
            >
              <span
                className="text-[10.5px]"
                style={{
                  color: "var(--color-ink-ghost)",
                  letterSpacing: "0.04em",
                }}
              >
                Shift-click the chip to skip this modal
              </span>
              <span
                className="text-[10.5px] tabular-nums"
                style={{ color: "var(--color-ink-ghost)" }}
              >
                {sourceName}
              </span>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

function ReasoningSkeleton() {
  return (
    <div className="space-y-1.5" aria-label="generating reasoning">
      <div
        className="h-2.5 rounded animate-pulse"
        style={{ background: "var(--color-rule-soft)", width: "92%" }}
      />
      <div
        className="h-2.5 rounded animate-pulse"
        style={{ background: "var(--color-rule-soft)", width: "84%" }}
      />
      <div
        className="h-2.5 rounded animate-pulse"
        style={{ background: "var(--color-rule-soft)", width: "55%" }}
      />
    </div>
  );
}
